-- Phase 0b migration: fix unique constraints to include entity_id
--
-- Without this migration, multi-entity projects fail when two entities share
-- the same line_item/year combination in historical_data or projected_financials.
-- The constraint must include entity_id so per-entity rows are independent.
--
-- Run AFTER migrate_phase0_entities.sql and migrate_phase2.sql.

-- ── 1. historical_data ──────────────────────────────────────────────────────

-- Drop old constraint (name generated by PostgreSQL convention)
ALTER TABLE historical_data
    DROP CONSTRAINT IF EXISTS historical_data_project_id_statement_type_line_item_year_key;

-- Add new constraint that includes entity_id.
-- NULL entity_id rows are unaffected: PostgreSQL treats each NULL as distinct,
-- so legacy single-entity rows (entity_id IS NULL) never collide with each other.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'uq_historical_data_entity'
    ) THEN
        ALTER TABLE historical_data
            ADD CONSTRAINT uq_historical_data_entity
            UNIQUE (project_id, entity_id, statement_type, line_item, year);
    END IF;
END $$;

-- ── 2. projected_financials ──────────────────────────────────────────────────

-- Drop old constraint (added by migrate_phase2.sql)
ALTER TABLE projected_financials
    DROP CONSTRAINT IF EXISTS projected_financials_unique;

-- Also drop the original pre-phase2 constraint name just in case
ALTER TABLE projected_financials
    DROP CONSTRAINT IF EXISTS projected_financials_project_id_statement_type_line_item_year_key;

-- Add new constraint including entity_id
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'uq_projected_financials_entity'
    ) THEN
        ALTER TABLE projected_financials
            ADD CONSTRAINT uq_projected_financials_entity
            UNIQUE (project_id, entity_id, scenario_id, statement_type, line_item, year);
    END IF;
END $$;

SELECT 'Phase 0b entity constraint migration complete' AS status;
